<?php return array(
    'root' => array(
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => 'ccfoun/api',
        'dev' => true,
    ),
    'versions' => array(
        'ccfoun/api' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'composer/package-versions-deprecated' => array(
            'pretty_version' => '1.11.99.1',
            'version' => '1.11.99.1',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./package-versions-deprecated',
            'aliases' => array(),
            'reference' => '7413f0b55a051e89485c5cb9f765fe24bb02a7b6',
            'dev_requirement' => false,
        ),
        'cweagans/composer-patches' => array(
            'pretty_version' => '1.7.1',
            'version' => '1.7.1.0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../cweagans/composer-patches',
            'aliases' => array(),
            'reference' => '9888dcc74993c030b75f3dd548bb5e20cdbd740c',
            'dev_requirement' => false,
        ),
        'doctrine/annotations' => array(
            'pretty_version' => '1.13.2',
            'version' => '1.13.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/annotations',
            'aliases' => array(),
            'reference' => '5b668aef16090008790395c02c893b1ba13f7e08',
            'dev_requirement' => false,
        ),
        'doctrine/cache' => array(
            'pretty_version' => '2.1.1',
            'version' => '2.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/cache',
            'aliases' => array(),
            'reference' => '331b4d5dbaeab3827976273e9356b3b453c300ce',
            'dev_requirement' => false,
        ),
        'doctrine/collections' => array(
            'pretty_version' => '1.6.8',
            'version' => '1.6.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/collections',
            'aliases' => array(),
            'reference' => '1958a744696c6bb3bb0d28db2611dc11610e78af',
            'dev_requirement' => false,
        ),
        'doctrine/common' => array(
            'pretty_version' => '3.1.2',
            'version' => '3.1.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/common',
            'aliases' => array(),
            'reference' => 'a036d90c303f3163b5be8b8fde9b6755b2be4a3a',
            'dev_requirement' => false,
        ),
        'doctrine/data-fixtures' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/data-fixtures',
            'aliases' => array(),
            'reference' => '51d3d4880d28951fff42a635a2389f8c63baddc5',
            'dev_requirement' => true,
        ),
        'doctrine/dbal' => array(
            'pretty_version' => '2.13.2',
            'version' => '2.13.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/dbal',
            'aliases' => array(),
            'reference' => '8dd39d2ead4409ce652fd4f02621060f009ea5e4',
            'dev_requirement' => false,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => 'v0.5.3',
            'version' => '0.5.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'reference' => '9504165960a1f83cc1480e2be1dd0a0478561314',
            'dev_requirement' => false,
        ),
        'doctrine/doctrine-bundle' => array(
            'pretty_version' => '2.4.2',
            'version' => '2.4.2.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../doctrine/doctrine-bundle',
            'aliases' => array(),
            'reference' => '4202ce675d29e70a8b9ee763bec021b6f44caccb',
            'dev_requirement' => false,
        ),
        'doctrine/doctrine-fixtures-bundle' => array(
            'pretty_version' => '3.4.0',
            'version' => '3.4.0.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../doctrine/doctrine-fixtures-bundle',
            'aliases' => array(),
            'reference' => '870189619a7770f468ffb0b80925302e065a3b34',
            'dev_requirement' => true,
        ),
        'doctrine/doctrine-migrations-bundle' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../doctrine/doctrine-migrations-bundle',
            'aliases' => array(),
            'reference' => '91f0a5e2356029575f3038432cc188b12f9d5da5',
            'dev_requirement' => false,
        ),
        'doctrine/event-manager' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/event-manager',
            'aliases' => array(),
            'reference' => '41370af6a30faa9dc0368c4a6814d596e81aba7f',
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'reference' => '9cf661f4eb38f7c881cac67c75ea9b00bf97b210',
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'reference' => 'd56bf6102915de5702778fe20f2de3b2fe570b5b',
            'dev_requirement' => false,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'reference' => 'e864bbf5904cb8f5bb334f99209b48018522f042',
            'dev_requirement' => false,
        ),
        'doctrine/migrations' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/migrations',
            'aliases' => array(),
            'reference' => '818e31703b4fb353c0c23caa714273fc64efa675',
            'dev_requirement' => false,
        ),
        'doctrine/orm' => array(
            'pretty_version' => '2.9.4',
            'version' => '2.9.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/orm',
            'aliases' => array(),
            'reference' => 'b19a13f4edfaa5806109cd899f5912a7df1547b5',
            'dev_requirement' => false,
        ),
        'doctrine/persistence' => array(
            'pretty_version' => '2.2.2',
            'version' => '2.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/persistence',
            'aliases' => array(),
            'reference' => '4ce4712e6dc84a156176a0fbbb11954a25c93103',
            'dev_requirement' => false,
        ),
        'doctrine/sql-formatter' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/sql-formatter',
            'aliases' => array(),
            'reference' => '56070bebac6e77230ed7d306ad13528e60732871',
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'reference' => 'c81f18a3efb941d8c4d2e025f6183b5c6d697307',
            'dev_requirement' => false,
        ),
        'firebase/php-jwt' => array(
            'pretty_version' => 'v5.4.0',
            'version' => '5.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../firebase/php-jwt',
            'aliases' => array(),
            'reference' => 'd2113d9b2e0e349796e72d2a63cf9319100382d2',
            'dev_requirement' => false,
        ),
        'friendsofphp/proxy-manager-lts' => array(
            'pretty_version' => 'v1.0.5',
            'version' => '1.0.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../friendsofphp/proxy-manager-lts',
            'aliases' => array(),
            'reference' => '006aa5d32f887a4db4353b13b5b5095613e0611f',
            'dev_requirement' => false,
        ),
        'laminas/laminas-code' => array(
            'pretty_version' => '4.4.2',
            'version' => '4.4.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-code',
            'aliases' => array(),
            'reference' => '54251ab2b16c41c6980387839496b235f5f6e10b',
            'dev_requirement' => false,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '2.3.2',
            'version' => '2.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'reference' => '71312564759a7db5b789296369c1a264efc43aad',
            'dev_requirement' => false,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.10.2',
            'version' => '1.10.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'reference' => '776f831124e9c62e1a2c601ecc52e776d8bb7220',
            'dev_requirement' => true,
            'replaced' => array(
                0 => '1.10.2',
            ),
        ),
        'nelmio/cors-bundle' => array(
            'pretty_version' => '2.1.1',
            'version' => '2.1.1.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../nelmio/cors-bundle',
            'aliases' => array(),
            'reference' => '0b964b665016dfb61dd0fd2bb8c24afb1ae45a93',
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.12.0',
            'version' => '4.12.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'reference' => '6608f01670c3cc5079e18c1dab1104e002579143',
            'dev_requirement' => true,
        ),
        'ocramius/package-versions' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.11.99',
            ),
        ),
        'ocramius/proxy-manager' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^2.1',
            ),
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'reference' => '97803eca37d319dfa7826cc2437fc020857acb53',
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'reference' => 'bae7c545bef187884426f042434e561ab1ddb182',
            'dev_requirement' => true,
        ),
        'php-amqplib/php-amqplib' => array(
            'pretty_version' => 'v2.0.2',
            'version' => '2.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-amqplib/php-amqplib',
            'aliases' => array(),
            'reference' => '682e3365f51c455f7a0bd32173d79922416fe9f0',
            'dev_requirement' => false,
        ),
        'php-http/async-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
            ),
        ),
        'php-http/client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
            ),
        ),
        'phpdocumentor/reflection-common' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-common',
            'aliases' => array(),
            'reference' => '1d01c49d4ed62f25aa84a747ad35d5a16924662b',
            'dev_requirement' => false,
        ),
        'phpdocumentor/reflection-docblock' => array(
            'pretty_version' => '5.2.2',
            'version' => '5.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-docblock',
            'aliases' => array(),
            'reference' => '069a785b2141f5bcf49f3e353548dc1cce6df556',
            'dev_requirement' => false,
        ),
        'phpdocumentor/type-resolver' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/type-resolver',
            'aliases' => array(),
            'reference' => '6a467b8989322d92aa1c8bf2bebcc6e5c2ba55c0',
            'dev_requirement' => false,
        ),
        'phpspec/prophecy' => array(
            'pretty_version' => '1.13.0',
            'version' => '1.13.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/prophecy',
            'aliases' => array(),
            'reference' => 'be1996ed8adc35c3fd795488a653f4b518be70ea',
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '9.2.6',
            'version' => '9.2.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'reference' => 'f6293e1b30a2354e8428e004689671b83871edde',
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '3.0.5',
            'version' => '3.0.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'reference' => 'aa4be8575f26070b100fccb67faabb28f21f66f8',
            'dev_requirement' => true,
        ),
        'phpunit/php-invoker' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-invoker',
            'aliases' => array(),
            'reference' => '5a10147d0aaf65b58940a0b72f71c9ac0423cc67',
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'reference' => '5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28',
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'reference' => '5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2',
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '9.5.4',
            'version' => '9.5.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'reference' => 'c73c6737305e779771147af66c96ca6a7ed8a741',
            'dev_requirement' => true,
        ),
        'psr/cache' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'reference' => '213f9dbc5b9bfbc4f8db86d2838dc968752ce13b',
            'dev_requirement' => false,
        ),
        'psr/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'reference' => '8622567409010282b7aeebe4bb841fe98b58dcaf',
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/event-dispatcher' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/event-dispatcher',
            'aliases' => array(),
            'reference' => 'dbefd12671e8a14ec7f180cab83036ed26714bb0',
            'dev_requirement' => false,
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
                1 => '1.0|2.0',
            ),
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'roave/security-advisories' => array(
            'pretty_version' => 'dev-latest',
            'version' => 'dev-latest',
            'type' => 'metapackage',
            'install_path' => NULL,
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '6da216d969efa7e52cc7d0af125b8c8bb9caed25',
            'dev_requirement' => true,
        ),
        'sebastian/cli-parser' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/cli-parser',
            'aliases' => array(),
            'reference' => '442e7c7e687e42adc03470c7b668bc4b2402c0b2',
            'dev_requirement' => true,
        ),
        'sebastian/code-unit' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit',
            'aliases' => array(),
            'reference' => '1fc9f64c0927627ef78ba436c9b17d967e68e120',
            'dev_requirement' => true,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'reference' => 'ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5',
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '4.0.6',
            'version' => '4.0.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'reference' => '55f4261989e546dc112258c7a75935a81a7ce382',
            'dev_requirement' => true,
        ),
        'sebastian/complexity' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/complexity',
            'aliases' => array(),
            'reference' => '739b35e53379900cc9ac327b2147867b8b6efd88',
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'reference' => '3461e3fccc7cfdfc2720be910d3bd73c69be590d',
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '5.1.3',
            'version' => '5.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'reference' => '388b6ced16caa751030f6a69e588299fa09200ac',
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '4.0.3',
            'version' => '4.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'reference' => 'd89cc98761b8cb5a1a235a6b703ae50d34080e65',
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'reference' => '23bd5951f7ff26f12d4e3242864df3e08dec4e49',
            'dev_requirement' => true,
        ),
        'sebastian/lines-of-code' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/lines-of-code',
            'aliases' => array(),
            'reference' => 'c1c2e997aa3146983ed888ad08b15470a2e22ecc',
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'reference' => '5c9eeac41b290a3712d88851518825ad78f45c71',
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'reference' => 'b4f479ebdbf63ac605d183ece17d8d7fe49c15c7',
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'reference' => 'cd9d8cf3c5804de4341c283ed787f099f5506172',
            'dev_requirement' => true,
        ),
        'sebastian/resource-operations' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/resource-operations',
            'aliases' => array(),
            'reference' => '0f4443cb3a1d92ce809899753bc0d5d5a8dd19a8',
            'dev_requirement' => true,
        ),
        'sebastian/type' => array(
            'pretty_version' => '2.3.4',
            'version' => '2.3.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/type',
            'aliases' => array(),
            'reference' => 'b8cd8a1c753c90bc1a0f5372170e3e489136f914',
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'reference' => 'c6c1022351a901512170118436c764e473f6de8c',
            'dev_requirement' => true,
        ),
        'sensio/framework-extra-bundle' => array(
            'pretty_version' => 'v6.1.5',
            'version' => '6.1.5.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../sensio/framework-extra-bundle',
            'aliases' => array(),
            'reference' => '62c5909f49cf74dccdf50a294511cc24be2f969c',
            'dev_requirement' => false,
        ),
        'symfony/amqp-messenger' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/amqp-messenger',
            'aliases' => array(),
            'reference' => '62736870b28c31041d48a1554e01261b03564d35',
            'dev_requirement' => false,
        ),
        'symfony/asset' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/asset',
            'aliases' => array(),
            'reference' => 'abe64fee9fa2978c730c84d0d6df760f2d9ddba0',
            'dev_requirement' => false,
        ),
        'symfony/browser-kit' => array(
            'pretty_version' => '5.2.x-dev',
            'version' => '5.2.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/browser-kit',
            'aliases' => array(),
            'reference' => 'ed7ebe262cef150742f5b61d48a94d37513c5758',
            'dev_requirement' => false,
        ),
        'symfony/cache' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/cache',
            'aliases' => array(),
            'reference' => 'b59303192fb99c8b3d3abc0b5975c7512fe6d1f4',
            'dev_requirement' => false,
        ),
        'symfony/cache-contracts' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/cache-contracts',
            'aliases' => array(),
            'reference' => 'c0446463729b89dd4fa62e9aeecc80287323615d',
            'dev_requirement' => false,
        ),
        'symfony/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'symfony/config' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/config',
            'aliases' => array(),
            'reference' => '32f6be0d0c2e204ff35759f9ee81d4f5e83b7acb',
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v5.2.14',
            'version' => '5.2.14.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'reference' => 'ffc2722adb0983451855c794c4bc7818d3c65fa2',
            'dev_requirement' => false,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'reference' => '7fb120adc7f600a59027775b224c13a33530dd90',
            'dev_requirement' => false,
        ),
        'symfony/debug-bundle' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/debug-bundle',
            'aliases' => array(),
            'reference' => '2cb76e25ca75afb0d52c1ba83d77cd4190ed5552',
            'dev_requirement' => false,
        ),
        'symfony/debug-pack' => array(
            'pretty_version' => 'v1.0.9',
            'version' => '1.0.9.0',
            'type' => 'symfony-pack',
            'install_path' => __DIR__ . '/../symfony/debug-pack',
            'aliases' => array(),
            'reference' => 'cfd5093378e9cafe500f05c777a22fe8a64a9342',
            'dev_requirement' => false,
        ),
        'symfony/dependency-injection' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dependency-injection',
            'aliases' => array(),
            'reference' => '2f0326ab0e142a3600b1b435cb3e852bc96264b6',
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'reference' => '5f38c8804a9e97d23e0c8d63341088cd8a22d627',
            'dev_requirement' => false,
        ),
        'symfony/doctrine-bridge' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/doctrine-bridge',
            'aliases' => array(),
            'reference' => '0212d2d1e17a3e7403475b76e26fc1f0f1add04b',
            'dev_requirement' => false,
        ),
        'symfony/doctrine-messenger' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/doctrine-messenger',
            'aliases' => array(),
            'reference' => 'f67e8f9f7d0e14d079c655c4c51440c388238e76',
            'dev_requirement' => false,
        ),
        'symfony/dom-crawler' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dom-crawler',
            'aliases' => array(),
            'reference' => 'c983279c00f723eef8da2a4b1522296c82dc75da',
            'dev_requirement' => false,
        ),
        'symfony/dotenv' => array(
            'pretty_version' => 'v5.2.14',
            'version' => '5.2.14.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dotenv',
            'aliases' => array(),
            'reference' => '12888c9c46ac750ec5c1381db5bf3d534e7d70cb',
            'dev_requirement' => false,
        ),
        'symfony/error-handler' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/error-handler',
            'aliases' => array(),
            'reference' => '7ca5fa510345f6b8def43b18c900852defaee362',
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'reference' => '6a32cd803f8ff33d84b709de3978f44a62e42961',
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'reference' => '69fee1ad2332a7cbab3aca13591953da9cdb7a11',
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0',
            ),
        ),
        'symfony/expression-language' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/expression-language',
            'aliases' => array(),
            'reference' => 'd4367d36217dd395b10f61649a6bf2c1367140d8',
            'dev_requirement' => false,
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'reference' => 'ed397ef25365b3db9f215af4ed5b1ec8a5b10989',
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'reference' => '17f50e06018baec41551a71a15731287dbaab186',
            'dev_requirement' => false,
        ),
        'symfony/flex' => array(
            'pretty_version' => 'v1.13.4',
            'version' => '1.13.4.0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../symfony/flex',
            'aliases' => array(),
            'reference' => 'd81196c3f3b544e32997b67e955fb8291fdfe770',
            'dev_requirement' => false,
        ),
        'symfony/form' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/form',
            'aliases' => array(),
            'reference' => '929811a7667aa5814f93a70974423870b14c05aa',
            'dev_requirement' => false,
        ),
        'symfony/framework-bundle' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/framework-bundle',
            'aliases' => array(),
            'reference' => '4e9ca1c60dba3b5e261eadd3b427bc115914b72b',
            'dev_requirement' => false,
        ),
        'symfony/http-client' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-client',
            'aliases' => array(),
            'reference' => '1895ede860a198803395a67738104211508b5ddc',
            'dev_requirement' => false,
        ),
        'symfony/http-client-contracts' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-client-contracts',
            'aliases' => array(),
            'reference' => '7e82f6084d7cae521a75ef2cb5c9457bbda785f4',
            'dev_requirement' => false,
        ),
        'symfony/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.2',
            ),
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v5.2.14',
            'version' => '5.2.14.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'reference' => '2a247de56fc8f5efdf1e098192128e8e509d370c',
            'dev_requirement' => false,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => 'v5.2.14',
            'version' => '5.2.14.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'reference' => '2c3b9af1047c477c527504a3509ab59e4fae0689',
            'dev_requirement' => false,
        ),
        'symfony/intl' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/intl',
            'aliases' => array(),
            'reference' => '23ae12a613eb77725c6ef6a15d37b0e9956c6a2a',
            'dev_requirement' => false,
        ),
        'symfony/mailer' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mailer',
            'aliases' => array(),
            'reference' => '75ea7f9e54c1bc49b6d7e3d6b20422f85b7ea3e4',
            'dev_requirement' => false,
        ),
        'symfony/maker-bundle' => array(
            'pretty_version' => 'v1.31.1',
            'version' => '1.31.1.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/maker-bundle',
            'aliases' => array(),
            'reference' => '4f57a44cef0b4555043160b8bf223fcde8a7a59a',
            'dev_requirement' => true,
        ),
        'symfony/messenger' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/messenger',
            'aliases' => array(),
            'reference' => 'a74654579bd227a846817ed59c42977194c43806',
            'dev_requirement' => false,
        ),
        'symfony/mime' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mime',
            'aliases' => array(),
            'reference' => '6ad63acd694b30e75fb2426b037e92859df73d6b',
            'dev_requirement' => false,
        ),
        'symfony/monolog-bridge' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/monolog-bridge',
            'aliases' => array(),
            'reference' => '2c3943d7c0100983f9c0a82807555273353e3539',
            'dev_requirement' => false,
        ),
        'symfony/monolog-bundle' => array(
            'pretty_version' => 'v3.7.0',
            'version' => '3.7.0.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/monolog-bundle',
            'aliases' => array(),
            'reference' => '4054b2e940a25195ae15f0a49ab0c51718922eb4',
            'dev_requirement' => false,
        ),
        'symfony/notifier' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/notifier',
            'aliases' => array(),
            'reference' => '08f557f018e080ea36d51b43a6552bf5396e9c83',
            'dev_requirement' => false,
        ),
        'symfony/options-resolver' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/options-resolver',
            'aliases' => array(),
            'reference' => '1935d2e5329aba28cbb9ef6cc5687d007619d96d',
            'dev_requirement' => false,
        ),
        'symfony/phpunit-bridge' => array(
            'pretty_version' => '5.2.x-dev',
            'version' => '5.2.9999999.9999999-dev',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/phpunit-bridge',
            'aliases' => array(),
            'reference' => '06e1bda76e73915b4afb2eb7669ca17b793d258a',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-iconv' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.23.1',
            'version' => '1.23.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'reference' => '16880ba9c5ebe3642d1995ab866db29270b36535',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-icu' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-icu',
            'aliases' => array(),
            'reference' => '4a80a521d6176870b6445cfb469c130f9cae1dda',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'reference' => '65bd267525e82759e7d8c4e8ceea44f398838e65',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'reference' => '8590a5f561694770bdcd3f9b5c69dde6945028e8',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.23.1',
            'version' => '1.23.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => '9174a3d80210dca8daa7f31fec659150bbeabfc6',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'reference' => 'fba8933c384d6476ab14fb7b8526e5287ca7e010',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.23.1',
            'version' => '1.23.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'reference' => '1100343ed1a92e3a38f9ae122fc0eb21602547be',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'reference' => 'e66119f3de95efc359483f810c4c3e6436279436',
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'reference' => 'd16634ee55b895bd85ec714dadc58e4428ecf030',
            'dev_requirement' => false,
        ),
        'symfony/profiler-pack' => array(
            'pretty_version' => 'v1.0.5',
            'version' => '1.0.5.0',
            'type' => 'symfony-pack',
            'install_path' => __DIR__ . '/../symfony/profiler-pack',
            'aliases' => array(),
            'reference' => '29ec66471082b4eb068db11eb4f0a48c277653f7',
            'dev_requirement' => false,
        ),
        'symfony/property-access' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/property-access',
            'aliases' => array(),
            'reference' => '82c6db3e4066ebc1993c377ae71090d0c8f0552c',
            'dev_requirement' => false,
        ),
        'symfony/property-info' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/property-info',
            'aliases' => array(),
            'reference' => 'f9dd1886f47db8ea494d97a4b8bfa494094f53f1',
            'dev_requirement' => false,
        ),
        'symfony/proxy-manager-bridge' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/proxy-manager-bridge',
            'aliases' => array(),
            'reference' => '76e61f33f6a34a340bf6e02211214f466e8e1dba',
            'dev_requirement' => false,
        ),
        'symfony/redis-messenger' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/redis-messenger',
            'aliases' => array(),
            'reference' => '451d5e2dc8d5e0ebb26edf9312292027f231bddc',
            'dev_requirement' => false,
        ),
        'symfony/routing' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'reference' => '983a19067308962592755f57d97ca1d1f1edd37b',
            'dev_requirement' => false,
        ),
        'symfony/security-bundle' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/security-bundle',
            'aliases' => array(),
            'reference' => 'bc36546f36355d7c0b56b23c44786b36904f838d',
            'dev_requirement' => false,
        ),
        'symfony/security-core' => array(
            'pretty_version' => 'v5.2.14',
            'version' => '5.2.14.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/security-core',
            'aliases' => array(),
            'reference' => '4ce2b1e532fb3bb591ad4efa8cc43afc9242a247',
            'dev_requirement' => false,
        ),
        'symfony/security-csrf' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/security-csrf',
            'aliases' => array(),
            'reference' => 'f0af6689451582e55f6b3439362e72e536e916e4',
            'dev_requirement' => false,
        ),
        'symfony/security-guard' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/security-guard',
            'aliases' => array(),
            'reference' => '9edddb0b4c97eb923ba9910050be80f539933c3b',
            'dev_requirement' => false,
        ),
        'symfony/security-http' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/security-http',
            'aliases' => array(),
            'reference' => '8d6fb4fb1bb0d4a11b30de85cbf77914c71175bc',
            'dev_requirement' => false,
        ),
        'symfony/serializer' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/serializer',
            'aliases' => array(),
            'reference' => '3c3afcc285c01c486d1c5504e7895026580495c4',
            'dev_requirement' => false,
        ),
        'symfony/serializer-pack' => array(
            'pretty_version' => 'v1.0.4',
            'version' => '1.0.4.0',
            'type' => 'symfony-pack',
            'install_path' => __DIR__ . '/../symfony/serializer-pack',
            'aliases' => array(),
            'reference' => '61173947057d5e1bf1c79e2a6ab6a8430be0602e',
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'reference' => 'f040a30e04b57fbcc9c6cbcf4dbaa96bd318b9bb',
            'dev_requirement' => false,
        ),
        'symfony/service-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'symfony/stopwatch' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/stopwatch',
            'aliases' => array(),
            'reference' => '24744393b122b8309bbcc7965972ae51a29a602d',
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v5.2.11',
            'version' => '5.2.11.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'reference' => 'ab6dc1c796bbceffbaf9ccbfb7a24feb641d6ee7',
            'dev_requirement' => false,
        ),
        'symfony/test-pack' => array(
            'pretty_version' => 'v1.0.7',
            'version' => '1.0.7.0',
            'type' => 'symfony-pack',
            'install_path' => __DIR__ . '/../symfony/test-pack',
            'aliases' => array(),
            'reference' => 'e61756c97cbedae00b7cf43b87abcfadfeb2746c',
            'dev_requirement' => false,
        ),
        'symfony/translation' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation',
            'aliases' => array(),
            'reference' => '7b4ef368b25bbb758a7bd5fe20349433e84220ed',
            'dev_requirement' => false,
        ),
        'symfony/translation-contracts' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation-contracts',
            'aliases' => array(),
            'reference' => '95c812666f3e91db75385749fe219c5e494c7f95',
            'dev_requirement' => false,
        ),
        'symfony/translation-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.3',
            ),
        ),
        'symfony/twig-bridge' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/twig-bridge',
            'aliases' => array(),
            'reference' => '243a7c6416fea3b91391f09831d8d04b2e42c0b1',
            'dev_requirement' => false,
        ),
        'symfony/twig-bundle' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/twig-bundle',
            'aliases' => array(),
            'reference' => '6f2aa369c4b7da19b3c864c48e35b26451c92e4e',
            'dev_requirement' => false,
        ),
        'symfony/validator' => array(
            'pretty_version' => 'v5.2.14',
            'version' => '5.2.14.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/validator',
            'aliases' => array(),
            'reference' => 'a46ac85624ad3418d455bb8f4ce452014c28518c',
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'reference' => 'd5f42c357a6672d4e5960bba85e437850e9a7abb',
            'dev_requirement' => false,
        ),
        'symfony/var-exporter' => array(
            'pretty_version' => 'v5.2.12',
            'version' => '5.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-exporter',
            'aliases' => array(),
            'reference' => 'b7898a65fc91e7c41de7a88c7db9aee9c0d432f0',
            'dev_requirement' => false,
        ),
        'symfony/web-profiler-bundle' => array(
            'pretty_version' => 'v5.2.13',
            'version' => '5.2.13.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/web-profiler-bundle',
            'aliases' => array(),
            'reference' => '380038080e46eb92b3a392de646fd32b632f1c77',
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v5.2.14',
            'version' => '5.2.14.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'reference' => 'ffe9c92e1a6c77c3ad5fc3a2ac16f0b8549dae10',
            'dev_requirement' => false,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'reference' => '34a41e998c2183e22995f158c581e7b5e755ab9e',
            'dev_requirement' => true,
        ),
        'twig/twig' => array(
            'pretty_version' => 'v3.3.2',
            'version' => '3.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/twig',
            'aliases' => array(),
            'reference' => '21578f00e83d4a82ecfa3d50752b609f13de6790',
            'dev_requirement' => false,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.10.0',
            'version' => '1.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'reference' => '6964c76c7804814a842473e0c8fd15bab0f18e25',
            'dev_requirement' => false,
        ),
    ),
);

